### ISSUE TITLE
CLOSED- Old Proposition

### ISSUE THREAD

**Issue by CryptoTrader88** [ProjectWyvern/WDPs#3]
old

**Comment by protinam** [comment]
Transaction information - if you want to propose the transfer of WYV tokens to an account: 

*Destination* 
You'll want to set the destination address to the WYV token address: `0x056017c55aE7AE32d12AeF7C679dF83A85ca75Ff`

*Bytecode*

You'll want to set the bytecode to the ABI encoding of the ERC20 transfer call. This can be generated, with the parameters you specified, using the following Javascript snippet:

```javascript
const Web3 = require('web3')
const fs = require('fs')
const BigNumber = require('bignumber.js')

const web3 = new Web3()
const tokenABI = JSON.parse(fs.readFileSync('./build/contracts/WyvernToken.json')).abi
const transfer = tokenABI.filter(m => m.name === 'transfer')[0]
const decimals = 18
const token = new BigNumber(10).pow(decimals)

const encoded = web3.eth.abi.encodeFunctionCall(transfer,
  ['0xD8379e095cca401491a48212C7fC37bcD28eEe28', token.mul(10000)]
)
console.log(encoded)
```
resulting in the following bytecode

`0xa9059cbb000000000000000000000000d8379e095cca401491a48212c7fc37bcd28eee2800000000000000000000000000000000000000000000021e19e0c9bab2400000`

**Comment by protinam** [comment]
As a Wyvern DAO shareholder, I'm very open to this concept - marketing is probably a productive use of the DAO funds right now, we'll need lots of beta testers for the Exchange. However, I have a few questions / concerns:

- 10,000 WYV seems like a lot for the DAO to spend, especially up front without escrow. A smaller pilot program - maybe 1000 WYV - with more conservative goals might be less risky.
- I'm not sure market capitalization is a good immediate metric; it can fluctuate a lot independent of the technical and community progress that will be necessary for long-term success of the Exchange. What do you think of instead targeting metrics such as active (voting or delegating) DAO shareholders or Wyvern Exchange users, and how would you organize a marketing strategy to achieve those goals?
- Can you provide some examples of the content marketing you intend to do, or past work (perhaps link the subreddit)?

**Comment by CryptoTrader88** [comment]
After a thorough discussion with Protinam, new issue created to replace this one:

https://github.com/ProjectWyvern/WDPs/issues/4
