### ISSUE TITLE
Special case ETH as a currency of exchange

### ISSUE THREAD

**Issue by dfinzer** [ProjectWyvern/WDPs#5]
## Preamble

    WDP: <to be assigned>
    Title: Special case ETH as a currency of exchange
    Author: dfinzer <devin.finzer@joinozone.com>
    Status: Draft
    Created: 2018-02-21

## Summary

Special case ETH as a currency of exchange, to reduce the requirement that ETH be wrapped as WETH in order to purchase assets using the Wyvern exchange.

## Motivation

Wrapping ETH in WETH introduces some friction to first-time users using the exchange, requiring at least one extra transaction. While it would be more elegant to only allow the exchange of assets using ERC20 tokens, it may be important for Wyvern adoption (by both users and frontends) to allow users to use ETH directly.

There are several existing marketplaces that allow users to purchase directly in ETH using custom smart contracts, and some might move to Wyvern if the friction were reduced. In the future, when the Ethereum currency itself becomes ERC20-compliant, we could remove this special-casing from the protocol to maintain it's simplicity.

## Description

I'd imagine this would require a change to the underlying protocol. The idea would be to fund a developer (likely @protinam since the change would likely be easy for him to implement) to do this. Alternatively, an outside developer could come in. I'd be curious to understand how difficult a contract upgrade would be and whether it would require an audit.

## Transaction Details

WIP

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by protinam** [comment]
I think my initial concerns were misplaced, it should be possible for the protocol to support both wrapped and unwrapped Ether, providing convenience now and ecosystem integration later.

Is it important for buyers and sellers to be able to make different choices (one using wrapped Ether and the other not), or is an implementation that requires agreement (either both using wrapped Ether or both using unwrapped Ether) sufficient?

If requiring agreement is fine, the zero-address can just be used as a sentinel value and special-cased in the fund transfer logic, e.g. (untested):

```diff
diff --git a/contracts/exchange/ExchangeCore.sol b/contracts/exchange/ExchangeCore.sol
index 656f270..12a06ce 100644
--- a/contracts/exchange/ExchangeCore.sol
+++ b/contracts/exchange/ExchangeCore.sol
@@ -392,7 +392,19 @@ contract ExchangeCore is ReentrancyGuarded {
 
         if (price > 0) {
             /* Debit buyer and credit seller. */
-            require(sell.paymentToken.transferFrom(buy.maker, sell.maker, price));
+            if (sell.paymentToken == address(0)) {
+              /* Special-case Ether, order must be matched by buyer. */
+              require(msg.value >= price);
+              sell.maker.transfer(price);
+              /* Allow overshoot for variable-price auctions, refund difference. */
+              uint diff = SafeMath.sub(msg.value, price);
+              if (diff > 0) {
+                buy.maker.transfer(diff);
+              }
+            } else {
+              /* ERC20 token. */
+              require(sell.paymentToken.transferFrom(buy.maker, sell.maker, price));
+            }
         }
 
         return price;
```

Does that sound like it would suit your use case?

I think payment for protocol upgrades is a necessary long-term strategy, but this one's pretty simple, no need to pay me. The DAO, however, will need to authorize the new version of the Exchange contract - and there is a mandatory 2-week delay in doing so (see https://github.com/ProjectWyvern/wyvern-ethereum/blob/master/contracts/registry/ProxyRegistry.sol#L26), so it makes sense to bundle other desired changes into this first upgrade if there are any.

**Comment by dfinzer** [comment]
That sounds great! Requiring agreement would definitely suit our case. Should I still submit this issue at https://dao.projectwyvern.com/proposals/create or is that unnecessary for this WDP?

**Comment by protinam** [comment]
The DAO proposal will need to call `startGrantAuthentication` on the `WyvernProxyRegistry` contract (https://github.com/ProjectWyvern/wyvern-ethereum/blob/master/contracts/registry/ProxyRegistry.sol#L39) with the address of the newly deployed version of the Exchange contract.

I think we should bundle one more minor change with this first protocol upgrade. At the moment, users still need to reauthorize new versions of the Exchange contract to transfer their tokens (ERC20 `approve`) - if we expect frequent protocol upgrades (and I think that capability may be useful), I think it makes sense to proxy the token transfers through a separate contract which uses the `WyvernProxyRegistry` authentication mechanism. This would mean that users only need to call ERC20 `approve` once (on the token transfer proxy contract) for all future versions of the core Exchange - as is already possible with nonfungible assets through the individual `AuthenticatedProxy` contracts.

Do you think that makes sense? Any other potential usability concerns worth addressing early on?

**Comment by dfinzer** [comment]
That sounds like a good one to bundle in! No other concerns at the moment, let me know when everything's ready for the DAO proposal.

**Comment by protinam** [comment]
I think it's worth also implementing the "split fee" concept proposed in https://github.com/ProjectWyvern/WDPs/issues/6 - they can easily be bundled into the same upgrade and need to work together anyways.

I'll write up an implementation covering (a) direct unwrapped Ether, (b) token approval proxy, and (c) split fees and see if our original auditor is willing to audit the new version (probably not *strictly* necessary, the attack surface shouldn't change much, but still prudent).

**Comment by protinam** [comment]
Closing in favor of #6.
